# Generated by Django 5.2.3 on 2025-07-30 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_knowledgepoint_brief_desc'),
        ('user_systems', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estim_duration', models.TimeField()),
                ('length', models.IntegerField()),
                ('next_activity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='CourseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.activity')),
                ('parent_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_systems.course')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_systems.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
