# Generated by Django 5.2.3 on 2025-07-30 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_knowledgepoint_brief_desc'),
        ('user_systems', '0005_alter_course_estim_duration_userknowledgedata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userknowledgedata',
            name='updated_on',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='SubtopicCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_covered_on', models.DateField()),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subtopic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
