# Generated by Django 5.1.7 on 2025-03-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityTag',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=40)),
                ('estim_min_duration', models.DurationField(verbose_name='Estimated MIN activity duration')),
                ('estim_max_duration', models.DurationField(verbose_name='Estimated MAX activity duration')),
                ('tags', models.ManyToManyField(blank=True, to='core.activitytag')),
            ],
        ),
    ]
