# Generated by Django 5.1.7 on 2025-04-30 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_activity_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kp_text', models.TextField(verbose_name='Text for this knowledge point')),
                ('kp_question', models.TextField(verbose_name='Question to assess this knowledge point')),
            ],
        ),
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('subtopic_num', models.IntegerField(verbose_name='Subtopic Number (according to curriculm order)')),
                ('info', models.TextField(verbose_name='Text for this subtopic, separate pages with \\page')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('name', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('topic_num', models.IntegerField(verbose_name='Topic Number (according to curriculm order)')),
                ('desc', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='kps',
            field=models.ManyToManyField(blank=True, to='core.knowledgepoint'),
        ),
        migrations.AddField(
            model_name='knowledgepoint',
            name='parent_subtopics',
            field=models.ManyToManyField(blank=True, to='core.subtopic'),
        ),
        migrations.AddField(
            model_name='activity',
            name='subtopics',
            field=models.ManyToManyField(blank=True, to='core.subtopic'),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='parent_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.topic'),
        ),
    ]
