# Generated by Django 5.1.7 on 2025-04-30 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_knowledgepoint_subtopic_topic_activity_kps_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityKps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.activity')),
                ('kp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.knowledgepoint')),
            ],
        ),
        migrations.RemoveField(
            model_name='activity',
            name='kps',
        ),
        migrations.AddField(
            model_name='activity',
            name='kps',
            field=models.ManyToManyField(blank=True, through='core.ActivityKps', to='core.knowledgepoint'),
        ),
        migrations.CreateModel(
            name='ActivitySubtopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.activity')),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subtopic')),
            ],
        ),
        migrations.RemoveField(
            model_name='activity',
            name='subtopics',
        ),
        migrations.AddField(
            model_name='activity',
            name='subtopics',
            field=models.ManyToManyField(blank=True, through='core.ActivitySubtopics', to='core.subtopic'),
        ),
        migrations.CreateModel(
            name='ActivityTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.activity')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.activitytag')),
            ],
        ),
        migrations.RemoveField(
            model_name='activity',
            name='tags',
        ),
        migrations.AddField(
            model_name='activity',
            name='tags',
            field=models.ManyToManyField(blank=True, through='core.ActivityTags', to='core.activitytag'),
        ),
        migrations.CreateModel(
            name='SubtopicPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.knowledgepoint')),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subtopic')),
            ],
        ),
        migrations.RemoveField(
            model_name='knowledgepoint',
            name='parent_subtopics',
        ),
        migrations.AddField(
            model_name='knowledgepoint',
            name='parent_subtopics',
            field=models.ManyToManyField(blank=True, through='core.SubtopicPoints', to='core.subtopic'),
        ),
    ]
