# Generated by Django 5.1.7 on 2025-04-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_activitykps_alter_activity_kps_activitysubtopics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='desc',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
