# Generated by Django 5.1.7 on 2025-04-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_topic_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopic',
            name='subtopic_num',
            field=models.IntegerField(verbose_name='Subtopic Number No.'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_num',
            field=models.IntegerField(verbose_name='Topic No.'),
        ),
    ]
