# Generated by Django 5.1.7 on 2025-04-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_subtopic_subtopic_num_alter_topic_topic_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopic',
            name='subtopic_num',
            field=models.IntegerField(verbose_name='Subtopic No.'),
        ),
    ]
