# Generated by Django 5.1.7 on 2025-04-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_subtopic_subtopic_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgepoint',
            name='brief_desc',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
