# Generated by Django 5.1.7 on 2025-03-11 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap_fill', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GapFillOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=40)),
                ('valid_positions_str', models.CharField(max_length=100)),
                ('gap_fill_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gap_fill.gapfilltext')),
            ],
        ),
    ]
